name: Test and lint

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip

      - name: Install dependencies
        run: pip install -r tests/requirements.txt

      - name: Run tests
        id: tests
        run: tests/run.py

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: tests/tests.diff
        if: ${{ failure() && steps.tests.conclusion == 'failure' }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: tests/.coverage
        if: ${{ !cancelled() }}

      - name: Regenerate usage
        id: update_usage
        run: |
          tests/update-usage.py
          git diff --exit-code README.md > tests/update-usage.diff

      - name: Upload 'regenerate usage' patch
        uses: actions/upload-artifact@v4
        with:
          name: update-usage
          path: tests/update-usage.diff
        if: ${{ failure() && steps.update_usage.conclusion == 'failure' }}
