name: Test and lint

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip

      - name: Install dependencies
        run: pip install -r tests/requirements.txt

      - name: Run tests
        id: tests
        run: tests/run.py

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: tests/tests.diff
        if: ${{ failure() && steps.tests.conclusion == 'failure' }}
